### ISSUE TITLE
Remove last commit? 

### ISSUE THREAD

**Issue by danielmlow** [sensein/group#20]
Hi @satra, I pushed this commit to this repo instead of to my fork to then do a PR:
https://github.com/sensein/group/commit/715f35c41677d072f81aba38e7065b41f8a7f663

The changes did not go live to website. Let me know if this is set or you can also delete the commit and I'll do the PR. 

Thanks

**Comment by satra** [comment]
you can still do a PR to this repo if you are planning to make additional changes. otherwise, i can push these changes to go life. i should add a checker to make sure things compile before we merge PRs.

**Comment by danielmlow** [comment]
Perhaps just remove that last commit and I'll do a PR. 

I need to fix how I added images in that commit, since I added the URLs (by right clicking and getting Copy Link Address on Google Images) but that won't work so I'll add the pngs to `images` dir instead

**Comment by satra** [comment]
i don't want to force a commit. so i would suggest building your PR on top of current master.

**Comment by danielmlow** [comment]
Here it is: 
https://github.com/sensein/group/pull/21
